controllers/FeedbackController.php
<?php

namespace app\controllers;

use app\models\GuestFeedback;
use Yii;
use app\models\Feedback;
use app\models\search\Feedback as FeedbackSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

class FeedbackController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    public function actions() {
        return [
//            'captcha' => [
//                'class' => 'yii\captcha\CaptchaAction',
//            ],
        ];
    }

    public function actionIndex()
    {
        $searchModel = new FeedbackSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionView($id) {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    public function actionCreate($template = null) {
        $model = new Feedback(['scenario' => Yii::$app->user->isGuest ? 'guest' : 'default']);

        if ($model->load(Yii::$app->request->post())) {
            if ('default' == $model->scenario) {
                $model->username = Yii::$app->user->identity->name;
            }
            if ($model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        }
        elseif (!Yii::$app->user->isGuest && $template) {
            switch($template) {
                case 'wallet':
                    $model->subject = 'Изменение кошелька';
                    $model->content = 'Измените мой кошелек ' . Yii::$app->user->identity->perfect . ' на ';
                    break;
            }
        }
        return $this->render('create', [
            'model' => $model,
        ]);
    }

    public function actionUpdate($id) {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Feedback model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Feedback the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Feedback::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

controllers/JournalController.php
<?php

namespace app\controllers;

use app\behaviors\Access;
use Yii;
use app\models\Record;
use app\models\search\Record as JournalSearch;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * JournalController implements the CRUD actions for Journal model.
 */
class JournalController extends Controller
{
    public function behaviors() {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
            'access' => [
                'class' => Access::className(),
                'plain' => ['index', 'view']
            ]
        ];
    }

    public function actionIndex() {
        $searchModel = new JournalSearch();

        $params = Yii::$app->request->queryParams;
        if (!Yii::$app->user->identity->isManager()) {
            if (empty($params['user'])) {
                return $this->redirect(['index', 'user' => Yii::$app->user->identity->name]);
            }
            elseif (!Yii::$app->user->identity->isManager() && $params['user'] != Yii::$app->user->identity->name) {
                throw new ForbiddenHttpException('Forbidden');
            }
        }
        $dataProvider = $searchModel->search($params);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionView($id) {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    public function actionDelete($id) {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Journal model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Record the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id) {
        if (($model = Record::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

controllers/UserController.php
<?php

namespace app\controllers;

use app\behaviors\Access;
use app\behaviors\Journal;
use app\models\Login;
use app\models\Password;
use app\models\Record;
use app\models\ResetRequest;
use app\models\Signup;
use app\models\UserData;
use Yii;
use app\models\User;
use app\models\search\User as UserSearch;
use yii\authclient\AuthAction;
use yii\authclient\ClientInterface;
use yii\helpers\Url;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

class UserController extends Controller
{
    public function behaviors() {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
            'access' => [
                'class' => Access::className(),
                'plain' => ['view', 'update'],
                'admin' => ['delete']
            ]
        ];
    }

    public function actions() {
        return [
            'social' => [
                'class' => AuthAction::className(),
                'successCallback' => [$this, 'social']
            ]
        ];
    }

    public function actionIndex() {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionView($name) {
        $model = $this->findModel($name);
        return $this->render('view', [
            'model' => $model,
        ]);
    }

    public function actionCreate() {
        $model = new User();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'name' => $model->name]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    public function actionUpdate($name) {
        $model = $this->findModel($name);

        if ($model->load(Yii::$app->request->post())) {
            if ($model->isNewRecord || (!Yii::$app->user->identity->isAdmin() && $model->isAttributeChanged('perfect', false))) {
                Yii::$app->session->setFlash('error', 'Wallet can change admin only');
            }
            else {
                return $this->redirect(['view', 'name' => $model->name]);
            }
        }
        return $this->render('update', [
            'model' => $model,
        ]);
    }

    public function actionDelete($name) {
        $this->findModel($name)->delete();
        return $this->redirect(['index']);
    }

    /**
     * @param string $name
     * @return User
     * @throws NotFoundHttpException
     */
    protected function findModel($name) {
        if (($model = User::findOne(['name' => $name])) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function social(ClientInterface $client) {
        $user_data = new UserData($client->getName(), $client->getUserAttributes());
        if (Yii::$app->user->isGuest) {
            $user = User::findSocial($user_data->getObjectName(), $user_data->getObjectName());
            if ($user) {
                Login::login($user);
            }
            else {
                $user_data->save();
            }
        }
        else {
            User::saveSocial(Yii::$app->user->identity, $user_data);
        }
        Yii::$app->session->set('social', $client->getName());
    }

    public function actionSignup() {
        $model = new User();
        User::loadUserData($model);
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $model->generateCode();
            $model->status = User::PLAIN;
            $model->save(false);
            if ($model->social) {
                User::saveSocial($model, $model->social);
            }
            $url = Url::to(['password', 'code' => $model->code], true);
            if ($model->sendEmail('html', [
                'subject' => Yii::$app->params['site']['name'] . ' ' . Yii::t('app', 'registration'),
                'content' => "Перейдите по <a href='$url'>ссылке</a>"
            ])) {
                Yii::$app->session->setFlash('info', Yii::t('app', 'Check your email'));
            }
            else {
                Yii::$app->session->setFlash('error', Yii::t('app', 'Email send error'));
            }
            return $this->redirect(['home/index']);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    public function actionLogin() {
        $model = new Login();

        if ($model->load(Yii::$app->request->post())) {
            $user = $model->getUser();
            if ($user) {
                $can = $user->canLogin();
                if ($can && $user->validatePassword($model->password)) {
                    if ($user->status > 0) {
                        Yii::$app->user->login($user);
                        return $this->redirect(['view', 'name' => $user->name]);
                    } else {
                        Yii::$app->session->setFlash('error', Yii::t('app', 'Ваш аккаунт заблокирован'));
                    }
                }
                else {
                    Journal::write('user', 'login_fail', $user->id);
                    if ($can) {
                        Yii::$app->session->setFlash('error', Yii::t('app', 'Invalid username or password'));
                    }
                    else {
                        $record = Record::find()->where([
                            'object_id' => $user->id,
                            'event' => 'login_fail'
                        ])->orderBy(['time' => SORT_DESC])->one();
                        Yii::$app->session->setFlash('error',
                            "Вы превысили максимальное количество попыток входа, вы сможете войти после $record->time");
                    }
                }
            }
            else {
                Yii::$app->session->setFlash('error', Yii::t('app', 'Invalid username or password'));
            }
        }

        return $this->render('login', [
            'model' => $model,
        ]);
    }

    public function actionLogout() {
        Yii::$app->user->logout();
        return $this->redirect(['home/index']);
    }

    public function actionPassword($code = null) {
        $message = null;
        $model = null;
        $user = $code ? User::findOne(['code' => $code]) :  Yii::$app->user->identity;
        if ($user) {
            $model = new Password([
                'scenario' => $code ? 'reset' : 'default',
                'user' => $user
            ]);

            if ($model->load(Yii::$app->request->post()) && $model->validate()) {
                if ($code) {
                    $user->code = null;
                    if (!$user->auth) {
                        $user->generateAuthKey();
                    }
                    $user->setPassword($model->new_password);
                    if ($user->save()) {
                        return $this->redirect(['user/login']);
                    } else {
                        $message = 'User validation error';
                    }
                } else {
                    if ($user->validatePassword($model->password)) {
                        $user->setPassword($model->new_password);
                        if ($user->save()) {
                            return $this->redirect(['user/view', 'name' => $user->name]);
                        }  else {
                            $message = 'User validation error';
                        }
                    }
                    else {
                        $model->addError('password', Yii::t('app', 'Invalid password'));
                    }
                }
            }
        }
        else {
            $message = Yii::t('app', 'Invalid code');
        }
        return $this->render('password', [
            'model' => $model,
            'message' => $message
        ]);
    }

    public function actionRequest() {
        $model = new ResetRequest();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $user = User::findOne(['email' => $model->email]);
            $user->generateCode();
            if ($user->save()) {
                $url = Url::to(['password', 'code' => $user->code], true);
                if($user->sendEmail('html', [
                    'subject' => Yii::$app->params['site']['name'] . ' ' . Yii::t('app', ' password reset'),
                    'content' => "Для восстановления пароля ерейдите по <a href='$url'>ссылке</a>"
                ])) {
                    Yii::$app->session->setFlash('info', Yii::t('app', 'Check your email'));
                    return $this->redirect(['site/index']);
                }
                else {
                    Yii::$app->session->setFlash('error', Yii::t('app', 'Email send error'));
                }
            }
        }
        return $this->render('request', [
            'model' => $model
        ]);
    }
}

views/user/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\User */
/* @var $form yii\widgets\ActiveForm */

function submit($label) {
    echo '<div class="form-group">';
    echo Html::submitButton($label, ['class' => 'btn btn-success']);
    echo '</div>';
}

echo '<div class="user-form">';
$form = ActiveForm::begin();

echo $form->field($model, 'name');
echo $form->field($model, 'email');
echo $form->field($model, 'phone');
echo $form->field($model, 'skype');
if ($model->isNewRecord || Yii::$app->user->identity->isAdmin()) {
    echo $form->field($model, 'perfect');
}
else {
    $a = Html::a('обратитесь к адмнинистратору', ['feedback/create', 'template' => 'wallet']);
    echo "<div class='form-group'>Для изменения кошелька $a</div>";
}

if (Yii::$app->user->isGuest) {
    submit(Yii::t('app', 'Signup'));
}
else {
    if ($model->isNewRecord) {
        submit(Yii::t('app', 'Create'));
    }
    else {
        submit(Yii::t('app', 'Update'));
    }
}

ActiveForm::end();

echo '</div>';

views/user/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\search\User */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'email') ?>

    <?= $form->field($model, 'hash') ?>

    <?= $form->field($model, 'auth') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/user/create.php
<?php

use yii\authclient\widgets\AuthChoice;
use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\User */

$this->title = Yii::$app->user->isGuest ? Yii::t('app', 'Signup') : Yii::t('app', 'Create User');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Users'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?php
    if (Yii::$app->user->isGuest) {
        echo '<br/>' . AuthChoice::widget(['baseAuthUrl' => ['social']]);
    }
    ?>
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/user/index.php
<?php

use app\models\User;
use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\search\User */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Users');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a(Yii::t('app', 'Create User'), ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            [
                'attribute' => 'name',
                'format' => 'html',
                'value' => function($model) {
                    return Html::a($model->name, ['view', 'name' => $model->name]);
                }
            ],
            'email:email',
            [
                'attribute' => 'status',
                'value' => function($model) {
                    return User::statuses()[$model->status];
                }
            ],
            'account',
            'perfect',
            'phone',
            'skype'
        ],
    ]); ?>

</div>

views/user/journal.php
<?php

/**
 * @var app\models\Record $record
 */

use app\models\User;

$info = $record->info;
if (!$info) {
    echo '';
}
elseif (isset($info['status'])) {
    echo Yii::t('app', 'Status') . ': ' . User::statuses()[$info['status']];
}
elseif (isset($info['account'])) {
    echo Yii::t('app', 'Account') . ': ' . $info['account'];
}
else {
    $key = key($info);
    echo "$key: " . $info[$key];
}

views/user/login.php
<?php

use yii\authclient\widgets\AuthChoice;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Login */
/* @var $form ActiveForm */
?>
<div class="user-login">
    <h1><?= Yii::t('app', 'Login') ?></h1>
    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'name') ?>
    <?= $form->field($model, 'password')->passwordInput() ?>
    <?= ''//$form->field($model, 'remember')->checkbox() ?>

    <div class="form-group">
        Вы можете <?= Html::a('восстановить пароль', ['request']) ?>
    </div>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Login'), ['class' => 'btn btn-primary']) ?>
    </div>
    <?php ActiveForm::end(); ?>
    <br/>
    <?= AuthChoice::widget(['baseAuthUrl' => ['social']]) ?>

</div><!-- user-login -->

views/user/password.php
<?php

use yii\authclient\widgets\AuthChoice;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/**
 * @var $this yii\web\View
 * @var $message string
 * @var $model app\models\Password
 * @var $form ActiveForm
 */

$reset = !$model || 'reset' == $model->scenario;
$this->title = Yii::t('app', $reset ? 'Reset Password' : 'Set Password');
if (!$reset) {
    $this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Users'), 'url' => ['index']];
    $this->params['breadcrumbs'][] = ['label' => $model->user_name, 'url' => ['view', 'name' => $model->user_name]];
    $this->params['breadcrumbs'][] = Yii::t('app', 'Password');
}

if ($message):
    echo "<div class=\"alert alert-danger\">$message</div>";
else:
    ?>
    <div class="user-password">
        <h1><?= $this->title ?></h1>
        <?php $form = ActiveForm::begin(); ?>

        <?php if (!$reset) {
            echo $form->field($model, 'password')->passwordInput();
        } ?>
        <?= $form->field($model, 'new_password')->passwordInput() ?>
        <?= $form->field($model, 'repeat_password')->passwordInput() ?>

        <div class="form-group">
            <?= Html::submitButton(Yii::t('app', 'Save'), ['class' => 'btn btn-primary']) ?>
        </div>
        <?php ActiveForm::end(); ?>
    </div>
<?php
endif;

views/user/request.php
<?php

use yii\authclient\widgets\AuthChoice;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/**
 * @var $this yii\web\View
 * @var $message string
 * @var $model app\models\Password
 * @var $form ActiveForm
 */

$this->title = Yii::t('app', 'Запрос на восстановление пароля');

?>
<div class="user-password">
    <h1><?= $this->title ?></h1>
    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'email') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Submit'), ['class' => 'btn btn-primary']) ?>
    </div>
    <?php ActiveForm::end(); ?>
</div>

views/user/signup.php
<?php

use yii\authclient\widgets\AuthChoice;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\User */
/* @var $form yii\widgets\ActiveForm */

$this->title = Yii::t('app', 'Signup');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Users'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="user-form">
    <h1><?= Yii::t('app', 'Signup') ?></h1>

    <?php $form = ActiveForm::begin(); ?>

    <br/>
    <?= AuthChoice::widget(['baseAuthUrl' => ['social']]) ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>
    <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>
    <?= $form->field($model, 'password')->passwordInput() ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Signup'), ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/user/update.php
<?php

use yii\authclient\widgets\AuthChoiceAsset;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\User */

AuthChoiceAsset::register($this);

$this->title = Yii::t('app', 'Update {modelClass}: ', [
    'modelClass' => 'User',
]) . ' ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Users'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'name' => $model->name]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');

$socials = $model->socials;
foreach($socials as $name => $id) {
    if ($id) {
        unset($socials[$name]);
    }
}
$socials = array_keys($socials);
?>
<div class="user-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

    <?php
    if (Yii::$app->user->identity->name == $model->name && !empty($socials)) {
        echo Html::tag('h2', 'Привязать');
        foreach($socials as $social) {
            echo Html::a(Html::tag('span', '', ['class' => "auth-icon $social"]),
                '/signup/' . $social, ['class' => "auth-link $social"]);
        }
    }
    ?>
</div>

views/user/view.php
<?php

use app\models\User;
use yii\authclient\widgets\AuthChoiceAsset;
use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\User */

AuthChoiceAsset::register($this);

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Users'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('app', 'Journal'), ['journal/index', 'user' => $model->name], ['class' => 'btn btn-primary']) ?>
        <?php
        if ($model->name == Yii::$app->user->identity->name) {
            echo Html::a(Yii::t('app', 'Change Password'), ['user/password', 'name' => $model->name], ['class' => 'btn btn-warning']);
        }
        ?>
        <?= Html::a(Yii::t('app', 'Update'), ['update', 'name' => $model->name], ['class' => 'btn btn-primary']) ?>
        <?php
        if (Yii::$app->user->identity->isAdmin()) {
            echo Html::a(Yii::t('app', 'Delete'), ['delete', 'name' => $model->name
            ], [
                'class' => 'btn btn-danger',
                'data' => [
                    'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                    'method' => 'post',
                ],
            ]);
        }
        ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'name',
            'email:email',
            [
                'attribute' => 'status',
                'value' => User::statuses()[$model->status]
            ],
            'account',
            'phone',
            'skype',
            'perfect'
        ],
    ]) ?>

    <?php
    foreach($model->getSocialLinks() as $social => $link) {
        echo Html::a(Html::tag('span', '', ['class' => "auth-client auth-icon $social"]),
            $link, ['class' => "auth-link $social"]);
    }
    ?>

</div>