models/Invoice.php
<?php

namespace app\models;

use app\behaviors\Journal;
use Yii;
use yii\db\ActiveRecord;

/**
 * This is the model class for table "invoice".
 *
 * @property integer $id
 * @property string $user_name
 * @property decimal $amount
 * @property string $status
 *
 * @property User $userName
 */
class Invoice extends ActiveRecord
{

    public static $statuses = [
        'create' => 'Создано',
        'invalid_amount' => 'Оплачена несоотвествующая сумма',
        'invalid_receiver' => 'Неправильний получатель',
        'invalid_batch' => 'Несоотвествие номеров транзакций',
        'invalid_response' => 'Неизвестний ответ сервера',
        'invalid_hash' => 'Ошибка подсчета хеш-суммы',
        'invalid_currency' => 'Оплата осуществлена не в USD',
        'insufficient_funds' => 'Недостаточно средств на счету пользователя',
        'no_qualification' => 'Пользователь не прошел квалификацию',
        'cancel' => 'Отмена',
        'fail' => 'Ошибка',
        'success' => 'Осуществлено'
    ];

    public static function tableName() {
        return 'invoice';
    }

    public function traceable() {
        return ['status'];
    }

    public function behaviors() {
        return [
            Journal::className()
        ];
    }

    public function rules() {
        return [
            [['user_name', 'amount'], 'required'],
            [['amount'], 'number'],
            [['user_name', 'status'], 'string', 'max' => 16]
        ];
    }

    public function attributeLabels() {
        return [
            'id' => Yii::t('app', 'ID'),
            'user_name' => Yii::t('app', 'User Name'),
            'amount' => Yii::t('app', 'Amount'),
            'status' => Yii::t('app', 'Status'),
        ];
    }

    public function getUser() {
        return $this->hasOne(User::className(), ['name' => 'user_name']);
    }

    public function saveStatus($status) {
        $this->status = $status;
        return $this->save();
    }

    public function __toString() {
        return "$$this->amount $this->user_name #$this->id";
    }
}

controllers/InvoiceController.php
<?php

namespace app\controllers;

use app\behaviors\Access;
use app\behaviors\NoTokenValidation;
use Yii;
use app\models\Invoice;
use app\models\search\Invoice as InvoiceSearch;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

class InvoiceController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'success' => ['post'],
                    'delete' => ['post'],
                ],
            ],

            'access' => [
                'class' => Access::className(),
                'plain' => ['success', 'fail', 'index', 'view', 'create'],
                'admin' => ['update', 'delete']
            ],

            'no_csrf' => [
                'class' => NoTokenValidation::className(),
                'only' => ['success', 'fail'],
            ]
        ];
    }

    public function actionIndex($user = null) {
        $searchModel = new InvoiceSearch();
        if (!Yii::$app->user->identity->isManager()) {
            if (!$user) {
                return $this->redirect(['index', 'user' => Yii::$app->user->identity->name]);
            }
            elseif (!Yii::$app->user->identity->isManager() && $user != Yii::$app->user->identity->name) {
                throw new ForbiddenHttpException('Forbidden');
            }
        }
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionView($id) {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    public function actionCreate() {
        $model = new Invoice([
            'user_name' => Yii::$app->user->identity->name,
            'status' => 'create'
        ]);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    public function actionUpdate($id) {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    public function actionDelete($id) {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    public function actionSuccess($id) {
        $transaction = Yii::$app->db->beginTransaction();
        $invoice = $this->findModel($id);
//        $invoice->scenario = 'payment';
        $string = $string= $_POST['PAYMENT_ID']
            .':'.$_POST['PAYEE_ACCOUNT']
            .':'.$_POST['PAYMENT_AMOUNT']
            .':'.$_POST['PAYMENT_UNITS']
            .':'.$_POST['PAYMENT_BATCH_NUM']
            .':'.$_POST['PAYER_ACCOUNT']
            .':'. Yii::$app->perfect->hashAlternateSecret()
            .':'.$_POST['TIMESTAMPGMT'];
        $user = $invoice->user;
        if (Yii::$app->user->identity->name != $invoice->user_name) {
            $transaction->rollBack();
            throw new ForbiddenHttpException('Вы можете изменять статус только своих оплат');
        }
        elseif ('success' == $invoice->status) {
            $transaction->rollBack();
            Yii::$app->session->setFlash('success', "Оплата #$id уже осуществлена");
        }
        elseif (strtoupper(md5($string)) != $_POST['V2_HASH']) {
            $invoice->saveStatus('invalid_hash');
            Yii::$app->session->setFlash('error', Invoice::$statuses['invalid_hash']);
        }
        elseif ($invoice->amount != $_POST['PAYMENT_AMOUNT']) {
            $invoice->saveStatus('invalid_amount');
            Yii::$app->session->setFlash('error', Invoice::$statuses['invalid_amount']);
        }
        elseif (Yii::$app->perfect->wallet != $_POST['PAYEE_ACCOUNT']) {
            $invoice->saveStatus('invalid_receiver');
            Yii::$app->session->setFlash('error', "Неправильный получатель " . $_POST['PAYEE_ACCOUNT']);
        }
        elseif ('USD' != $_POST['PAYMENT_UNITS']) {
            $invoice->saveStatus('invalid_currency');
            Yii::$app->session->setFlash('error', Invoice::$statuses['invalid_currency']);
        }
        else {
            $user->account += $invoice->amount;
            if ($invoice->saveStatus('success') && $user->save()) {
                Yii::$app->session->setFlash('success', "Оплата #$id осуществелна");
            }
            else {
                $invoice->saveStatus('fail');
                Yii::$app->session->setFlash('error', "При сохранении оплаты #$id случилась ошибка");
            }
        }
        $transaction->commit();

        return $this->render('view', [
            'model' => $invoice
        ]);
    }

    public function actionFail($id) {
        $invoice = $this->findModel($id);

        if (Yii::$app->user->identity->name != $invoice->user_name) {
            throw new ForbiddenHttpException('Вы можете изменять статус только своих оплат');
        }
        else {
            $invoice->saveStatus('cancel');
            Yii::$app->session->setFlash('error', "Вы не осуществили оплату");
        }

        return $this->render('view', [
            'model' => $invoice
        ]);
    }

    /**
     * Finds the Invoice model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Invoice the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Invoice::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/invoice/_form.php
<?php

use app\models\Invoice;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Invoice */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="invoice-form">

    <?php $form = ActiveForm::begin();

    if (Yii::$app->user->identity->isManager()) {
        echo $form->field($model, 'user_name')->textInput(['maxlength' => true]);
        echo $form->field($model, 'status')->dropDownList(Invoice::$statuses);
    }
    echo$form->field($model, 'amount')->textInput(['maxlength' => true]);
    ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Update'),
            ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/invoice/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\search\Invoice */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="invoice-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'user_name') ?>

    <?= $form->field($model, 'amount') ?>

    <?= $form->field($model, 'status') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/invoice/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Invoice */

$this->title = Yii::t('app', 'Create Invoice');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Invoices'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="invoice-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/invoice/index.php
<?php

use app\models\Invoice;
use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\search\Invoice */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Invoices');
$this->params['breadcrumbs'][] = $this->title;

$actions = ['class' => 'yii\grid\ActionColumn'];
if (!Yii::$app->user->identity->isManager()) {
    $actions['template'] = '{view}';
}
?>
<div class="invoice-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a(Yii::t('app', 'Create Invoice'), ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'user_name',
            'amount',
            [
                'attribute' => 'status',
                'value' => function($model) {
                    return Invoice::$statuses[$model->status];
                }
            ],

            $actions,
        ],
    ]); ?>

</div>

views/invoice/journal.php
<?php

/**
 * @var app\models\Record $record
 */

use app\models\Invoice;

$info = $record->info;
if (!$info) {
    echo '';
}
elseif (isset($info['status'])) {
    echo Invoice::$statuses[$info['status']];
}

views/invoice/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Invoice */

$this->title = Yii::t('app', 'Update {modelClass}: ', [
    'modelClass' => 'Invoice',
]) . ' ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Invoices'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="invoice-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/invoice/view.php
<?php

use app\models\Invoice;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Invoice */

$this->title = $model;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Invoices'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="invoice-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?php if (Yii::$app->user->identity->isManager()): ?>
            <?= Html::a(Yii::t('app', 'Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
            <?= Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->id], [
                'class' => 'btn btn-danger',
                'data' => [
                    'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                    'method' => 'post',
                ],
            ]) ?>
        <?php
        elseif ('success' != $model->status && $model->amount > 0):
            echo Html::beginForm('https://perfectmoney.is/api/step1.asp', 'POST');
            echo Html::hiddenInput('PAYEE_ACCOUNT', Yii::$app->perfect->wallet);
            echo Html::hiddenInput('PAYMENT_AMOUNT', $model->amount);
            echo Html::hiddenInput('PAYEE_NAME', Yii::$app->name);
            echo Html::hiddenInput('PAYMENT_UNITS', 'USD');
            echo Html::hiddenInput('PAYMENT_ID', $model->status);
            echo Html::hiddenInput('STATUS_URL', Url::to(['invoice/view', 'id' => $model->id], true));
            echo Html::hiddenInput('PAYMENT_URL', Url::to(['invoice/success', 'id' => $model->id], true));
            echo Html::hiddenInput('NOPAYMENT_URL', Url::to(['invoice/fail', 'id' => $model->id], true));
            echo Html::hiddenInput('BAGGAGE_FIELDS', 'USER_NAME');
            echo Html::hiddenInput('USER_NAME', Yii::$app->user->identity->name);
            echo Html::button(Yii::t('app', 'Pay'), [
                'name' => 'PAYMENT_METHOD',
                'type' => 'submit',
                'class' => 'btn btn-success'
            ]);
            echo Html::endForm();
        endif;
        ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'user_name',
            'amount',
            [
                'attribute' => 'status',
                'value' => Invoice::$statuses[$model->status]
            ]
        ],
    ]) ?>

</div>